### ISSUE TITLE
Add option for overriding table names

### ISSUE THREAD

**Issue by pizzot** [fordnox/php-queue-manager#4]
Would be good to add an option to overrdide the table names. `queue` and `message` are too generic. If this could be changed to at least `queue_queue` and `queue_message` that would perfectly suffice I think. 

Alternatively an option can be added for table prefix or for completely custom table names.

Let me know your thoughts and if you need help implementing.

Thanks

**Comment by fordnox** [comment]
@okneloper could you open pull request? i will merge it

**Comment by pizzot** [comment]
@fordnox do you see any use in the prefix or custom names? As I said, simple table names change would be just fine for me, wondering if more than that is worth the hassle?

**Comment by fordnox** [comment]
@okneloper just for backwards compatibility. Someone is already using this library, i do not want to change it and break something for them. 

Adding new method to set table names would be fine

**Comment by pizzot** [comment]
hi @fordnox 
I have made the chnage just to realize it's been on the master branch since 2015?

Just need to bump the version no.

**Comment by fordnox** [comment]
@okneloper resolved?

**Comment by pizzot** [comment]
Yeah, if you could release this change though, as currently one needs to require "dev-master" which is not very good for production.

**Comment by fordnox** [comment]
new version released

**Comment by pizzot** [comment]
Thanks
